import React from 'react';
import styled from "styled-components";

export default function LoadingSpinier() {
  return (<>
  <StyledContainer>

    <div className="loadingio-spinner-double-ring-uhk9ptllo6"><div className="ldio-hl499l8niw">
<div></div>
<div></div>
<div><div></div></div>
<div><div></div></div>
</div></div>
  </StyledContainer>

  
  </>);
}


const StyledContainer = styled.div`

    display:grid;
    place-items: center;
    height:100vh;

@keyframes ldio-hl499l8niw {
  0% { transform: rotate(0) }
  100% { transform: rotate(360deg) }
}
.ldio-hl499l8niw div { box-sizing: border-box!important }
.ldio-hl499l8niw > div {
  position: absolute;
  width: 144px;
  height: 144px;
  top: 28px;
  left: 28px;
  border-radius: 50%;
  border: 16px solid #000;
  border-color: #0a0a0a transparent #0a0a0a transparent;
  animation: ldio-hl499l8niw 1s linear infinite;
}

.ldio-hl499l8niw > div:nth-child(2), .ldio-hl499l8niw > div:nth-child(4) {
  width: 108px;
  height: 108px;
  top: 46px;
  left: 46px;
  animation: ldio-hl499l8niw 1s linear infinite reverse;
}
.ldio-hl499l8niw > div:nth-child(2) {
  border-color: transparent #28292f transparent #28292f
}
.ldio-hl499l8niw > div:nth-child(3) { border-color: transparent }
.ldio-hl499l8niw > div:nth-child(3) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-hl499l8niw > div:nth-child(3) div:before, .ldio-hl499l8niw > div:nth-child(3) div:after { 
  content: "";
  display: block;
  position: absolute;
  width: 16px;
  height: 16px;
  top: -16px;
  left: 48px;
  background: #0a0a0a;
  border-radius: 50%;
  box-shadow: 0 128px 0 0 #0a0a0a;
}
.ldio-hl499l8niw > div:nth-child(3) div:after {
  left: -16px;
  top: 48px;
  box-shadow: 128px 0 0 0 #0a0a0a;
}

.ldio-hl499l8niw > div:nth-child(4) { border-color: transparent; }
.ldio-hl499l8niw > div:nth-child(4) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-hl499l8niw > div:nth-child(4) div:before, .ldio-hl499l8niw > div:nth-child(4) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 16px;
  height: 16px;
  top: -16px;
  left: 30px;
  background: #28292f;
  border-radius: 50%;
  box-shadow: 0 92px 0 0 #28292f;
}
.ldio-hl499l8niw > div:nth-child(4) div:after {
  left: -16px;
  top: 30px;
  box-shadow: 92px 0 0 0 #28292f;
}
.loadingio-spinner-double-ring-uhk9ptllo6 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #f1f2f3;
}
.ldio-hl499l8niw {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-hl499l8niw div { box-sizing: content-box; }
/* generated by https://loading.io/ */

    
`